[package]
name = "ndarray-100-exercises"
version = "0.1.0"
authors = ["Jaroslaw Skrzypek <skrzypek.jarek@gmail.com>"]

[dependencies]
ndarray = "0.7.2"
ndarray-rand = "0.3.1"
rand = "0.3"
approx = "0.1.1"
